PROJECT_NAME = Calculator
SRC = calculator.c\
test_calculator.c

INC = unity

TEST = unity/unity.c

$(PROJECT_NAME).exe : $(SRC) $(TEST)
	gcc -I $(INC) $(SRC) $(TEST) -o $(PROJECT_NAME).exe
